-- 0044_canonical_academic_catalogue
-- BMI University 204-course canonical catalogue
-- NOTE: courses.level column was already added in a prior migration run.
PRAGMA foreign_keys = OFF;
INSERT OR IGNORE INTO departments (id, name, code, faculty_id, description) VALUES
  ('d-apologetics','Department of Christian Apologetics','DCA',(SELECT id FROM faculties WHERE code='FTM' LIMIT 1),'Apologetics and cultural engagement'),
  ('d-worship','Department of Worship Arts','DWA',(SELECT id FROM faculties WHERE code='FTM' LIMIT 1),'Worship leadership and liturgical arts'),
  ('d-missions','Department of Missions and Evangelism','DME',(SELECT id FROM faculties WHERE code='FTM' LIMIT 1),'Cross-cultural missions and evangelism'),
  ('d-preaching','Department of Preaching and Homiletics','DPH',(SELECT id FROM faculties WHERE code='FTM' LIMIT 1),'Biblical preaching and homiletics'),
  ('d-grad-counsel','Department of Graduate Counseling','DGC',(SELECT id FROM faculties WHERE code='FCE' LIMIT 1),'Graduate Christian counseling');
INSERT OR IGNORE INTO programs (id, name, code, degree_type, level, department_id, duration_years, total_credit_hours, mode_of_study, description, icon) VALUES
  ('p-dip-ministry','Diploma in Ministry','DIM','Diploma','diploma','d-ministry',1,48,'blended','A one-year foundation programme equipping students with core biblical and ministry competencies.','/images/diploma-icon.png'),
  ('p-ma-apologetics','MA in Christian Apologetics','MACA','Master of Arts','graduate','d-apologetics',2,60,'blended','Advanced apologetics and cultural engagement.','/images/masters-icon.png'),
  ('p-ma-leadership','MA in Christian Leadership','MACL','Master of Arts','graduate','d-ministry',2,60,'blended','Advanced Christian leadership for ministry and organizational contexts.','/images/masters-icon.png');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='APO101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='APOL101');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='CED101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='EDUC101');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='WOR101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='WRSH101');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='PAST501' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='MDIV501');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='LEAD510' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='MDIV510');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='RES701' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='THD701');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='RES702' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='THD702');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='CED701' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='DCE701');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='LANG502' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='BIBL501');
UPDATE enrollments SET course_id=(SELECT id FROM courses WHERE code='LANG501' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='BIBL502');
UPDATE student_course_registrations SET course_id=(SELECT id FROM courses WHERE code='APO101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='APOL101');
UPDATE student_course_registrations SET course_id=(SELECT id FROM courses WHERE code='CED101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='EDUC101');
UPDATE student_course_registrations SET course_id=(SELECT id FROM courses WHERE code='WOR101' LIMIT 1) WHERE course_id IN (SELECT id FROM courses WHERE code='WRSH101');
DELETE FROM courses WHERE code IN ('APOL101','APOL501','EDUC101','EDUC501','WRSH101','MDIV501','MDIV510','GCBS101','GCBS102','GCCS101','GCSF101','GCSF102','THD701','THD702','DCE701','THEO502','BIBL501','BIBL502','DMIN710');
INSERT OR REPLACE INTO courses (code, title, description, credits, term, capacity, level) VALUES
('BIBL101', 'Introduction to the Bible', 'Foundational introduction to the structure, canon, historical context, and major themes of the Holy Scriptures.', 3, 'Ongoing', 150, '100'),
('BIBL102', 'Old Testament Survey I', 'Survey of the Pentateuch and Historical Books, tracing the redemptive historical narrative of Israel.', 3, 'Ongoing', 150, '100'),
('BIBL103', 'New Testament Survey I', 'Introduction to the Gospels and Acts, focusing on the life, ministry, death, and resurrection of Jesus Christ and the early church.', 3, 'Ongoing', 150, '100'),
('BIBL104', 'New Testament Survey II', 'Introduction to the Epistles and Revelation, examining apostolic theology and eschatological themes.', 3, 'Ongoing', 150, '100'),
('BIBL201', 'Old Testament Survey II', 'Comprehensive study of Old Testament Poetic, Wisdom, and Prophetic Literature within historical and theological contexts.', 3, 'Ongoing', 150, '200'),
('BIBL202', 'New Testament Survey II', 'In-depth survey of the Apostolic writings from Romans to Revelation with emphasis on Christology and Christian living.', 3, 'Ongoing', 150, '200'),
('BIBL210', 'Biblical Hermeneutics', 'Principles and methods of sound biblical interpretation, exegesis, grammatical-historical hermeneutics, and avoiding misinterpretation.', 3, 'Ongoing', 150, '200'),
('BIBL301', 'Biblical Theology', 'Thematic and developmental study of key redemptive themes spanning the Old and New Testaments.', 3, 'Ongoing', 150, '300'),
('BIBL302', 'Pentateuch', 'Detailed literary, historical, and theological study of Genesis through Deuteronomy.', 3, 'Ongoing', 150, '300'),
('BIBL303', 'Historical Books', 'Theological and historical analysis of Joshua through Esther.', 3, 'Ongoing', 150, '300'),
('BIBL304', 'Wisdom and Poetic Literature', 'Exegetical and practical exploration of Job, Psalms, Proverbs, Ecclesiastes, and Song of Songs.', 3, 'Ongoing', 150, '300'),
('BIBL305', 'Prophetic Literature', 'Historical contexts, prophetic calling, messianic themes, and theological message of the Major and Minor Prophets.', 3, 'Ongoing', 150, '300'),
('BIBL306', 'Gospels and Acts', 'Comparative study of the Four Gospels and Luke''s account of early church expansion in Acts.', 3, 'Ongoing', 150, '300'),
('BIBL307', 'Pauline Epistles', 'Exegetical study of the life, letters, and theology of the Apostle Paul.', 3, 'Ongoing', 150, '300'),
('BIBL308', 'General Epistles and Revelation', 'Theological examination of Hebrews, James, Peter, John, Jude, and the Apocalypse.', 3, 'Ongoing', 150, '300'),
('BIBL401', 'Advanced Biblical Exegesis', 'Methodological synthesis of textual criticism, grammatical exegesis, and contextual application of biblical passages.', 3, 'Ongoing', 150, '400'),
('BIBL402', 'Biblical Backgrounds and Archaeology', 'Ancient Near Eastern and Greco-Roman archaeological and cultural backgrounds illuminating Scripture.', 3, 'Ongoing', 150, '400'),
('BIBL501', 'Advanced Biblical Interpretation', 'Graduate-level hermeneutical models, critical methodologies, and theological synthesis of biblical texts.', 3, 'Ongoing', 150, '500'),
('LANG201', 'Biblical Greek I', 'Introduction to Koine Greek grammar, vocabulary, noun declensions, and basic verb paradigms.', 3, 'Ongoing', 150, '200'),
('LANG202', 'Biblical Greek II', 'Continuation of Biblical Greek I, covering irregular verbs, participles, syntax, and translation of selected New Testament passages.', 3, 'Ongoing', 150, '200'),
('LANG301', 'Biblical Hebrew I', 'Introduction to biblical Hebrew alphabet, vowel pointing, basic grammar, and core vocabulary.', 3, 'Ongoing', 150, '300'),
('LANG302', 'Biblical Hebrew II', 'Continuation of Biblical Hebrew I, strong and weak verbs, syntax, and translation from the Hebrew Scriptures.', 3, 'Ongoing', 150, '300'),
('LANG501', 'Advanced Greek Exegesis', 'Graduate-level syntax and guided exegesis of theological treatises and Pauline letters in the Greek New Testament.', 3, 'Ongoing', 150, '500'),
('LANG502', 'Advanced Hebrew Exegesis', 'Graduate-level exegesis of narrative, poetic, and prophetic Hebrew passages with discourse analysis.', 3, 'Ongoing', 150, '500'),
('THEO101', 'Systematic Theology I', 'Introduction to Christian doctrine: attributes of God, Trinity, creation, providence, and the person and work of Christ.', 3, 'Ongoing', 150, '100'),
('THEO102', 'Systematic Theology II', 'Continuation of Christian doctrine: sin, salvation, Holy Spirit, church, sacraments, and eschatology.', 3, 'Ongoing', 150, '100'),
('THEO103', 'Biblical Hermeneutics Foundations', 'Introductory methods for interpreting biblical scripture in personal and ministry contexts.', 3, 'Ongoing', 150, '100'),
('THEO201', 'Christian Theology I', 'Core Christian doctrines including God, Trinity, Revelation, Creation, and Christology.', 3, 'Ongoing', 150, '200'),
('THEO202', 'Christian Theology II', 'Doctrines of Pneumatology, Ecclesiology, Salvation, Christian Ethics, and Eschatology.', 3, 'Ongoing', 150, '200'),
('THEO301', 'Biblical Theology', 'Examination of progressive divine revelation across covenants and biblical theological trajectories.', 3, 'Ongoing', 150, '300'),
('THEO302', 'Systematic Theology I', 'Prolegomena, Theology Proper, Divine Decrees, Anthropology, and Hamartiology.', 3, 'Ongoing', 150, '300'),
('THEO303', 'Systematic Theology II', 'Christology, Pneumatology, Soteriology, Ecclesiology, and Eschatology in historical and contemporary debate.', 3, 'Ongoing', 150, '300'),
('THEO304', 'Theology of the Holy Spirit and the Church', 'Pneumatological foundations, spiritual gifts, Pentecostal/Charismatic perspectives, and church renewal.', 3, 'Ongoing', 150, '300'),
('THEO305', 'Christology', 'The person, natures, incarnational glory, atonement, and resurrected reign of Jesus Christ.', 3, 'Ongoing', 150, '300'),
('THEO306', 'Doctrine of Salvation', 'Soteriological models, regeneration, justification, sanctification, and eternal redemption.', 3, 'Ongoing', 150, '300'),
('THEO307', 'Eschatology', 'Biblical prophecies, the Second Coming, resurrection, judgment, millenarian views, and the New Creation.', 3, 'Ongoing', 150, '300'),
('THEO308', 'Christian Ethics', 'Biblical moral philosophy applied to contemporary social, biomedical, sexual, and leadership dilemmas.', 3, 'Ongoing', 150, '300'),
('THEO309', 'Theology and Culture', 'Theological discernment of cultural movements, media, postmodernity, and public theology.', 3, 'Ongoing', 150, '300'),
('THEO310', 'Philosophy of Religion', 'Philosophical inquiry into the existence of God, problem of evil, epistemology of faith, and religious realism.', 3, 'Ongoing', 150, '300'),
('THEO401', 'Contemporary Theology', 'Major twentieth- and twenty-first-century theological developments, movements, and thinkers.', 3, 'Ongoing', 150, '400'),
('THEO402', 'Theology of Mission', 'The Missio Dei, biblical foundations of global evangelism, and contextualization of the Gospel.', 3, 'Ongoing', 150, '400'),
('THEO403', 'World Religions and Christian Theology', 'Theological assessment of Islam, Hinduism, Buddhism, traditional religions, and Christian uniqueness.', 3, 'Ongoing', 150, '400'),
('THEO501', 'Advanced Systematic Theology', 'Seminar in comprehensive dogmatics, classical controversies, and contemporary theological debates.', 3, 'Ongoing', 150, '500'),
('THEO510', 'Historical and Contemporary Theology', 'Integration of patristic, reformational, and modern theological trajectories in graduate research.', 3, 'Ongoing', 150, '500'),
('CHST101', 'Church History I', 'Survey of Christian history from the Apostolic era through the Reformation (100–1517 AD).', 3, 'Ongoing', 150, '100'),
('CHST102', 'Church History II', 'Survey of Christian history from the Reformation to the modern era, including global church movements.', 3, 'Ongoing', 150, '100'),
('CHST201', 'Church History I', 'Early Church, ecumenical councils, medieval Christianity, and the Protestant Reformation.', 3, 'Ongoing', 150, '200'),
('CHST202', 'Church History II', 'Post-Reformation developments, evangelical awakenings, modern missions, and global Christianity.', 3, 'Ongoing', 150, '200'),
('CHST301', 'History of Christian Doctrine', 'Historical development of core Christian dogmas from Patristic controversies to modern confessions.', 3, 'Ongoing', 150, '300'),
('CHST501', 'Advanced Church History', 'Graduate-level analysis of primary historical documents, historiography, and key reform movements.', 3, 'Ongoing', 150, '500'),
('CHST502', 'Church History and Global Christianity', 'The rise of Christianity in the Global South, African church history, and cross-cultural missional history.', 3, 'Ongoing', 150, '500'),
('MIN101', 'Introduction to Ministry', 'Survey of vocational ministry callings, church leadership structures, and pastoral ethics.', 3, 'Ongoing', 150, '100'),
('MIN102', 'Homiletics I: Preaching Foundations', 'Foundations of sermon construction, biblical exposition, and pulpit communication.', 3, 'Ongoing', 150, '100'),
('MIN201', 'Introduction to Christian Ministry', 'Biblical call to ministry, shepherding principles, pastoral care, and ministerial integrity.', 3, 'Ongoing', 150, '200'),
('MIN202', 'Church and Ministry Administration', 'Practical church governance, financial stewardship, volunteer management, and legal compliance.', 3, 'Ongoing', 150, '200'),
('MIN301', 'Ministry Ethics and Professional Practice', 'Ethical conduct for ministers, confidentiality, power dynamics, accountability, and boundaries.', 3, 'Ongoing', 150, '300'),
('MIN302', 'Missions and Cross-Cultural Ministry', 'Theological and anthropological principles for effective intercultural ministry and evangelism.', 3, 'Ongoing', 150, '300'),
('MIN401', 'Ministry Practicum', 'Supervised practical field ministry placement in local churches or approved Christian organizations.', 3, 'Ongoing', 150, '400'),
('MIN501', 'Advanced Ministry Studies', 'Graduate seminar examining complex institutional, ethical, and pastoral challenges in contemporary ministry.', 3, 'Ongoing', 150, '500'),
('PAST301', 'Pastoral Care and Counseling', 'Principles and practice of pastoral counseling, hospital visitation, grief care, and crisis intervention.', 3, 'Ongoing', 150, '300'),
('PAST501', 'Pastoral Theology & Practice', 'Advanced pastoral theology, pastoral leadership, liturgy, crisis ministry, and minister''s soul care.', 3, 'Ongoing', 150, '500'),
('MISS201', 'Introduction to Christian Missions', 'Biblical mandate for missions, historical overview of modern missionary movements, and intercultural awareness.', 3, 'Ongoing', 150, '200'),
('MISS302', 'Cross-Cultural Missions & Engagement', 'Contextualization, indigenous church planting principles, and cross-cultural missional strategies.', 3, 'Ongoing', 150, '300'),
('MISS501', 'Global Missiology and Intercultural Ministry', 'Advanced missiological frameworks, urban mission dynamics, and missionary strategy in a globalized world.', 3, 'Ongoing', 150, '500'),
('MISS502', 'Theology of Mission', 'Biblical, historical, and contemporary perspectives on Christian mission, evangelism, and Kingdom expansion.', 3, 'Ongoing', 150, '500'),
('LEAD201', 'Foundations of Christian Leadership', 'Biblical theology of servant leadership, personal character, self-leadership, and visionary integrity.', 3, 'Ongoing', 150, '200'),
('LEAD301', 'Leadership and Team Development', 'Building, mentoring, empowering, and evaluating collaborative ministry teams.', 3, 'Ongoing', 150, '300'),
('LEAD302', 'Conflict Management and Reconciliation', 'Biblical models of dispute resolution, institutional peacemaking, and restorative leadership.', 3, 'Ongoing', 150, '300'),
('LEAD401', 'Strategic Leadership for Churches', 'Strategic planning, organizational alignment, vision casting, and execution in ministry organizations.', 3, 'Ongoing', 150, '400'),
('LEAD402', 'Church Growth and Development', 'Principles of healthy church expansion, community engagement, and multiplication dynamics.', 3, 'Ongoing', 150, '400'),
('LEAD501', 'Foundations of Christian Leadership', 'Graduate-level leadership theory, biblical leadership paradigms, and executive ministry stewardship.', 3, 'Ongoing', 150, '500'),
('LEAD502', 'Leadership Formation and Character', 'Spiritual disciplines, emotional intelligence, resilience, and ethical fortitude in senior leadership.', 3, 'Ongoing', 150, '500'),
('LEAD503', 'Team Leadership and Development', 'High-performance team dynamics, delegation, staff culture cultivation, and coaching.', 3, 'Ongoing', 150, '500'),
('LEAD504', 'Conflict Management and Reconciliation', 'Mediation strategies, organizational crisis intervention, and restoring broken relationships.', 3, 'Ongoing', 150, '500'),
('LEAD505', 'Strategic Leadership for Ministry', 'Long-term planning, systems thinking, change management, and risk governance in Christian ministries.', 3, 'Ongoing', 150, '500'),
('LEAD506', 'Organizational Leadership', 'Organizational behavior, institutional governance, board dynamics, and institutional lifecycle transitions.', 3, 'Ongoing', 150, '500'),
('LEAD510', 'Church Polity and Leadership', 'Models of church government, congregational bylaws, ecclesiastical order, and executive administration.', 3, 'Ongoing', 150, '500'),
('LEAD601', 'Advanced Christian Leadership', 'Advanced seminar in visionary leadership, strategic communication, and executive decision-making.', 3, 'Ongoing', 150, '600'),
('LEAD602', 'Leadership, Culture and Change', 'Leading cultural change in organizations, managing transitions, and overcoming institutional inertia.', 3, 'Ongoing', 150, '600'),
('LEAD603', 'Leadership Research Methods', 'Quantitative and qualitative research applied to organizational leadership and ecclesial systems.', 3, 'Ongoing', 150, '600'),
('LEAD604', 'Leadership Practicum and Capstone', 'Culminating applied leadership project addressing a real-world ministry or institutional challenge.', 3, 'Ongoing', 150, '600'),
('CED101', 'Christian Education Foundations', 'Introduction to the philosophy, history, and practice of Christian education in the church and society.', 3, 'Ongoing', 150, '100'),
('CED201', 'Foundations of Christian Education', 'Biblical, theological, and historical foundations of Christian teaching ministries.', 3, 'Ongoing', 150, '200'),
('CED202', 'Philosophy of Christian Education', 'Comparative study of educational philosophies viewed through a biblical worldview.', 3, 'Ongoing', 150, '200'),
('CED301', 'Educational Psychology', 'Human learning theories, cognitive development, motivation, and spiritual maturation in Christian context.', 3, 'Ongoing', 150, '300'),
('CED302', 'Teaching and Learning in Christian Contexts', 'Instructional methodologies, lesson planning, active learning, and creative pedagogical techniques.', 3, 'Ongoing', 150, '300'),
('CED303', 'Curriculum Design and Development', 'Principles of curriculum development, learning outcomes, material selection, and evaluation.', 3, 'Ongoing', 150, '300'),
('CED304', 'Teaching the Bible', 'Transformational Bible teaching pedagogy for varied developmental age groups.', 3, 'Ongoing', 150, '300'),
('CED305', 'Discipleship and Spiritual Formation', 'Educational frameworks for intentional Christian discipleship and spiritual growth within congregations.', 3, 'Ongoing', 150, '300'),
('CED306', 'Christian Education in the Local Church', 'Organizing Sunday school, small groups, Bible studies, and church-wide Christian education programs.', 3, 'Ongoing', 150, '300'),
('CED307', 'Christian Education for Children', 'Child development, creative storytelling, family ministry partnerships, and children''s church ministry.', 3, 'Ongoing', 150, '300'),
('CED308', 'Christian Education for Youth', 'Adolescent psychology, contemporary youth culture, campus ministry, and mentoring teens.', 3, 'Ongoing', 150, '300'),
('CED309', 'Adult Christian Education', 'Andragogy, adult life stages, small-group leadership, and senior adult ministry.', 3, 'Ongoing', 150, '300'),
('CED401', 'Educational Leadership', 'Leadership principles for Christian school headmasters, church educational directors, and administrators.', 3, 'Ongoing', 150, '400'),
('CED402', 'Assessment and Evaluation', 'Formative and summative assessment tools, program evaluation, and student progress measurements.', 3, 'Ongoing', 150, '400'),
('CED403', 'Educational Technology and Online Learning', 'Integrating digital learning platforms, multimedia tools, and distance learning into Christian instruction.', 3, 'Ongoing', 150, '400'),
('CED404', 'Christian Education Practicum', 'Supervised student teaching experience in Christian schools, church education departments, or camps.', 3, 'Ongoing', 150, '400'),
('CED501', 'Advanced Christian Education', 'Graduate exploration of advanced educational philosophy, transformational pedagogy, and leadership.', 3, 'Ongoing', 150, '500'),
('CED601', 'Advanced Curriculum and Instruction', 'Curriculum theory, systemic instructional design, and institutional accreditation standards.', 3, 'Ongoing', 150, '600'),
('CED701', 'Christian Education Research', 'Doctoral research methodologies, empirical study design, and dissertation preparation in Christian Education.', 3, 'Ongoing', 150, '700'),
('COUN101', 'Introduction to Christian Counseling', 'Foundational overview of biblical counseling principles, empathetic listening, and soul care.', 3, 'Ongoing', 150, '100'),
('COUN201', 'Christian Counseling / Marriage & Family', 'Biblical counseling foundations, marriage enrichment, parenting guidance, and counseling ethics for ministry.', 3, 'Ongoing', 150, '200'),
('COUN501', 'Christian Counseling Foundations', 'Theological integration of psychology and theology, counseling models, and Christian worldview foundations.', 3, 'Ongoing', 150, '500'),
('COUN502', 'Marriage and Family Counseling', 'Family systems theory, premarital counseling, marital conflict resolution, and divorce recovery.', 3, 'Ongoing', 150, '500'),
('COUN503', 'Trauma and Crisis Counseling', 'Intervention models for acute trauma, grief, PTSD, disaster mental health, and bereavement care.', 3, 'Ongoing', 150, '500'),
('COUN504', 'Counseling Ethics and Professional Practice', 'Legal and ethical standards in professional counseling, informed consent, confidentiality, and liability.', 3, 'Ongoing', 150, '500'),
('COUN505', 'Helping Relationships', 'Core counseling skills, therapeutic alliance, active listening, and empathetic communication.', 3, 'Ongoing', 150, '500'),
('COUN506', 'Lifespan Development', 'Physical, cognitive, psychological, and spiritual development across the human lifespan.', 3, 'Ongoing', 150, '500'),
('COUN507', 'Psychopathology', 'Diagnostic criteria, DSM classification, mood disorders, anxiety, and theological perspectives on mental illness.', 3, 'Ongoing', 150, '500'),
('COUN508', 'Multicultural Counseling', 'Cross-cultural competence, addressing diversity, ethnicity, socioeconomic factors, and counseling in global contexts.', 3, 'Ongoing', 150, '500'),
('COUN509', 'Group Dynamics', 'Theory and practice of group counseling, group facilitation, stages of group development, and support groups.', 3, 'Ongoing', 150, '500'),
('COUN510', 'Counseling Assessment', 'Psychological assessment, testing instruments, clinical intake interviews, and appraisal techniques.', 3, 'Ongoing', 150, '500'),
('COUN511', 'Crisis and Addictions Counseling', 'Substance use disorders, behavioral addictions, recovery models, and spiritual deliverance pathways.', 3, 'Ongoing', 150, '500'),
('COUN512', 'Career Counseling', 'Career development theories, vocational calling, assessment, and life planning.', 3, 'Ongoing', 150, '500'),
('COUN601', 'Advanced Christian Counseling Models and Practice', 'Advanced integration of cognitive-behavioral, psychodynamic, and narrative therapies with Christian faith.', 3, 'Ongoing', 150, '600'),
('COUN602', 'Clinical Counseling Practicum I', 'Supervised clinical counseling practicum with individual client hours and faculty case supervision.', 3, 'Ongoing', 150, '600'),
('COUN603', 'Clinical Counseling Practicum II', 'Advanced supervised clinical field placement with direct client contact and clinical review.', 3, 'Ongoing', 150, '600'),
('COUN604', 'Clinical Counseling Practicum III', 'Comprehensive internship capstone in an approved clinical counseling facility.', 3, 'Ongoing', 150, '600'),
('COUN605', 'Counseling Research', 'Research design, outcome evaluation, and evidence-based practice in Christian mental health counseling.', 3, 'Ongoing', 150, '600'),
('APO101', 'Introduction to Christian Apologetics', 'Foundational arguments for God''s existence, resurrection of Christ, reliability of Scripture, and common objections.', 3, 'Ongoing', 150, '100'),
('APO201', 'Apologetics & World Religions', 'Defending the Christian faith, engaging other religions and cults, and applying apologetics in contemporary culture.', 3, 'Ongoing', 150, '200'),
('APO501', 'Foundations of Christian Apologetics', 'Classical, evidential, presuppositional, and cumulative-case apologetic methodologies.', 3, 'Ongoing', 150, '500'),
('APO502', 'Cultural Apologetics', 'Engaging contemporary arts, literature, secular philosophies, and cultural worldviews with the Gospel.', 3, 'Ongoing', 150, '500'),
('APO503', 'Philosophy of Religion', 'Epistemological, metaphysical, and philosophical arguments concerning theism, evil, and miracles.', 3, 'Ongoing', 150, '500'),
('APO504', 'Apologetics and World Religions', 'Engaging Islam, Eastern religions, New Age spirituality, and secular humanism.', 3, 'Ongoing', 150, '500'),
('APO505', 'Apologetics, Science and Faith', 'Cosmology, evolutionary biology, fine-tuning, neuroscience, and the historical harmony of science and Christianity.', 3, 'Ongoing', 150, '500'),
('APO506', 'Practical Apologetics and Evangelism', 'Conversational apologetics, street evangelism, debating techniques, and discipling skeptics.', 3, 'Ongoing', 150, '500'),
('APO601', 'Advanced Christian Apologetics', 'Seminar addressing complex objections: problem of suffering, moral relativism, and biblical violence.', 3, 'Ongoing', 150, '600'),
('APO602', 'Apologetics and Contemporary Culture', 'Post-truth society, identity politics, transhumanism, and defending Christian anthropology.', 3, 'Ongoing', 150, '600'),
('APO603', 'Apologetics Research Methods', 'Formulating apologetic theses, primary source critical analysis, and scholarly writing.', 3, 'Ongoing', 150, '600'),
('APO604', 'Advanced Practical Apologetics', 'Public debates, media communication, podcasting, and campus outreach apologetics.', 3, 'Ongoing', 150, '600'),
('WOR101', 'Worship Leadership Foundations', 'Principles of corporate worship planning, music leadership, liturgy, and the theology of worship.', 3, 'Ongoing', 150, '100'),
('WOR201', 'Theology of Worship', 'Trinitarian worship theology, covenantal worship paradigms, and glorifying God in the assembly.', 3, 'Ongoing', 150, '200'),
('WOR202', 'Biblical Foundations of Worship', 'Tabernacle, Temple, Synagogue, and Early Church worship models in the Old and New Testaments.', 3, 'Ongoing', 150, '200'),
('WOR203', 'Worship History and Traditions', 'Historical development of liturgies, hymnody, the Reformation, and modern contemporary worship movements.', 3, 'Ongoing', 150, '200'),
('WOR204', 'Worship Leadership and Team Building', 'Auditioning, pastoring, discipling, and organizing musicians, singers, and technical production teams.', 3, 'Ongoing', 150, '200'),
('WOR301', 'Worship Planning and Service Design', 'Thematic service flow, liturgical seasons, sacramental integration, and creative service architecture.', 3, 'Ongoing', 150, '300'),
('WOR302', 'Music and Congregational Worship', 'Arranging, vocal coaching, band directing, song selection, and congregational singing dynamics.', 3, 'Ongoing', 150, '300'),
('WOR303', 'Worship Ministry Technology', 'Live sound reinforcement, digital audio workstations, lighting, video projection, and streaming technology.', 3, 'Ongoing', 150, '300'),
('WOR304', 'Worship Arts and Creativity', 'Visual arts, drama, dance, graphic design, and artistic expression in corporate worship.', 3, 'Ongoing', 150, '300'),
('WOR305', 'Worship and Culture', 'Multicultural worship styles, indigenous musical idioms, and contextualizing corporate worship.', 3, 'Ongoing', 150, '300'),
('WOR306', 'Worship Pastoral Care', 'Pastoring the worship team, avoiding burnout, ministering through times of personal grief and triumph.', 3, 'Ongoing', 150, '300'),
('WOR401', 'Advanced Worship Leadership', 'Executive leadership of large worship ministries, multisite coordination, and creative arts direction.', 3, 'Ongoing', 150, '400'),
('WOR402', 'Worship Administration and Production', 'Budgeting, copyright compliance (CCLI), facility acoustics, and large-scale event production.', 3, 'Ongoing', 150, '400'),
('WOR403', 'Worship in Contemporary Church Contexts', 'Analyzing modern worship trends, song writing, theological vetting of worship lyrics, and church trends.', 3, 'Ongoing', 150, '400'),
('WOR404', 'Worship Practicum I', 'Supervised worship leading internship in a partner local church congregation.', 3, 'Ongoing', 150, '400'),
('WOR405', 'Worship Practicum II and Capstone', 'Senior capstone recital or produced worship event accompanied by comprehensive theological portfolio.', 3, 'Ongoing', 150, '400'),
('SPFM201', 'Introduction to Spiritual Formation', 'Personal discipleship, identity in Christ, character, prayer, calling, worship, and Holy Spirit life.', 3, 'Ongoing', 150, '200'),
('SPFM301', 'Spiritual Formation and Discipleship', 'Practicing classical spiritual disciplines: solitude, fasting, meditation, Sabbath, and journaling.', 3, 'Ongoing', 150, '300'),
('SPFM401', 'Advanced Spiritual Formation', 'Spiritual direction, soul care models, discerning the voice of God, and spiritual leadership.', 3, 'Ongoing', 150, '400'),
('SPFM501', 'Spiritual Formation Foundations', 'Theology and history of Christian spirituality, spiritual disciplines, and lifelong vocational endurance.', 3, 'Ongoing', 150, '500'),
('SPFM502', 'Spiritual Disciplines and Christian Character', 'Cultivating virtue, mortification of sin, fruit of the Spirit, and Christ-like maturity.', 3, 'Ongoing', 150, '500'),
('SPFM503', 'Spiritual Formation in Ministry', 'Soul care for pastors and leaders, avoiding burnout, spiritual accompaniment, and renewal.', 3, 'Ongoing', 150, '500'),
('SPFM601', 'Advanced Spiritual Formation', 'Supervised spiritual direction, retreat leadership, and mystical theology in historical perspective.', 3, 'Ongoing', 150, '600'),
('PREA201', 'Homiletics / Biblical Preaching', 'Preparing and delivering effective biblical sermons, manuscripting, outlining, and vocal delivery.', 3, 'Ongoing', 150, '200'),
('PREA301', 'Introduction to Homiletics', 'Theology of preaching, sermon structures, audience analysis, and expository sermon construction.', 3, 'Ongoing', 150, '300'),
('PREA401', 'Biblical Preaching', 'Preaching from varied biblical genres: narrative, law, poetry, prophecy, epistle, and apocalyptic.', 3, 'Ongoing', 150, '400'),
('PREA501', 'Preaching Principles and Practice', 'Graduate homiletics, hermeneutical exegesis to homiletical delivery, and video critique.', 3, 'Ongoing', 150, '500'),
('PREA502', 'Advanced Biblical Preaching', 'Evangelistic, prophetic, and doctrinal preaching in diverse cultural and ecclesiastical environments.', 3, 'Ongoing', 150, '500'),
('PREA601', 'Advanced Homiletics', 'Homiletical theory, rhetorical analysis, master preaching seminars, and sermon series architecture.', 3, 'Ongoing', 150, '600'),
('PREA701', 'Doctoral Preaching Seminar', 'Doctoral colloquium on theological, hermeneutical, and rhetorical dynamics of pulpit proclamation.', 3, 'Ongoing', 150, '700'),
('PREA710', 'Preaching in the Post-Christendom Era', 'Advanced homiletics addressing secularized contexts, pluralistic audiences, and deconstructive thought.', 3, 'Ongoing', 150, '700'),
('EVAN201', 'Evangelism & Discipleship', 'Personal and lifestyle evangelism, apologetic conversations, follow-up, and disciple-making.', 3, 'Ongoing', 150, '200'),
('EVAN301', 'Personal Evangelism', 'Relational outreach, sharing the Gospel effectively, answering objections, and leading people to faith.', 3, 'Ongoing', 150, '300'),
('EVAN401', 'Evangelism and Church Growth', 'Congregational evangelism strategies, outreach campaigns, community service, and multiplication.', 3, 'Ongoing', 150, '400'),
('EVAN501', 'Advanced Evangelism', 'Graduate study in cultural contextualization, mass evangelism, and discipling converts in hostile regions.', 3, 'Ongoing', 150, '500'),
('DISC201', 'Discipleship and Spiritual Formation', 'Jesus'' method of disciple-making, relational investment, multiplication, and spiritual reproduction.', 3, 'Ongoing', 150, '200'),
('DISC301', 'Discipleship Ministry', 'Designing small-group discipleship pathways, mentoring models, and accountability structures.', 3, 'Ongoing', 150, '300'),
('DISC401', 'Advanced Discipleship', 'Discipling leaders, generational disciple-making movements, and holistic community impact.', 3, 'Ongoing', 150, '400'),
('ECLE201', 'The Local Church & Kingdom Building', 'Ecclesiology, church planting, church growth, community impact, and marketplace ministry.', 3, 'Ongoing', 150, '200'),
('ECLE501', 'Ecclesiology', 'Biblical and historical doctrine of the Church, its marks, sacraments, structure, and mission.', 3, 'Ongoing', 150, '500'),
('ECLE502', 'The Local Church and Kingdom Building', 'Mobilizing congregations for community transformation, social justice, and marketplace evangelism.', 3, 'Ongoing', 150, '500'),
('ECLE503', 'Church Planting and Development', 'Assessment, demographic analysis, funding, launch teams, and first-phase multiplication of church plants.', 3, 'Ongoing', 150, '500'),
('ECLE504', 'Church Growth and Community Impact', 'Demographic research, community assessment, and metrics for healthy holistic church growth.', 3, 'Ongoing', 150, '500'),
('ECLE601', 'Advanced Ecclesiology', 'Ecumenical dialogues, missional ecclesiology, and the church''s role in twenty-first-century society.', 3, 'Ongoing', 150, '600'),
('DIGI201', 'Technology, Media & the Church in the Digital Age', 'Media literacy, biblical truth in the digital age, technology stewardship, social media strategy, and church software.', 3, 'Ongoing', 150, '200'),
('DIGI301', 'Technology and Ministry', 'Practical use of digital presentation, audiovisual tools, database management, and virtual ministry.', 3, 'Ongoing', 150, '300'),
('DIGI401', 'Digital Ministry', 'Online church communities, hybrid ministry models, digital pastoral care, and digital evangelism.', 3, 'Ongoing', 150, '400'),
('DIGI501', 'Technology, Media and the Church in the Digital Age', 'Graduate inquiry into theological implications of artificial intelligence, digital community, and transhumanism.', 3, 'Ongoing', 150, '500'),
('DIGI502', 'Church Management Systems and Digital Administration', 'Implementation of ChMS, cloud security, digital giving, data privacy, and online church governance.', 3, 'Ongoing', 150, '500'),
('DIGI503', 'Social Media and Digital Ministry Strategy', 'Content creation, digital storytelling, online discipleship funnels, and viral engagement for ministries.', 3, 'Ongoing', 150, '500'),
('SUPM201', 'Supernatural Ministry / Healing & Deliverance', 'Biblical study of faith, prayer, healing, spiritual gifts, deliverance, and spiritual warfare with theological balance.', 3, 'Ongoing', 150, '200'),
('SUPM501', 'Supernatural Ministry', 'Biblical theology of miracles, the miraculous in church history, and academic engagement with signs and wonders.', 3, 'Ongoing', 150, '500'),
('SUPM502', 'Healing and Deliverance Ministry', 'Theological frameworks and pastoral protocols for prayer ministry, emotional healing, and spiritual deliverance.', 3, 'Ongoing', 150, '500'),
('SUPM503', 'Spiritual Warfare and Discernment', 'Biblical demonology, cosmic spiritual warfare, and discerning spiritual deception in contemporary culture.', 3, 'Ongoing', 150, '500'),
('SUPM504', 'Holy Spirit, Gifts and Ministry', 'Exegetical study of charismata in 1 Corinthians 12-14, Romans 12, and their operation in modern assemblies.', 3, 'Ongoing', 150, '500'),
('RES401', 'Undergraduate Research and Capstone', 'Senior research thesis, bibliographic research, primary sources, and comprehensive academic defense.', 3, 'Ongoing', 150, '400'),
('RES501', 'Graduate Research Methods', 'Graduate-level theological research, bibliographic methodology, scholarly writing, and thesis proposal design.', 3, 'Ongoing', 150, '500'),
('RES601', 'Advanced Research Methods', 'Qualitative, quantitative, and mixed-method research methodologies for theological and ministerial inquiries.', 3, 'Ongoing', 150, '600'),
('RES701', 'Doctoral Research Seminar', 'Doctoral dissertation proposal defense, methodology validation, and literature review synthesis.', 3, 'Ongoing', 150, '700'),
('RES702', 'Doctoral Dissertation Seminar', 'Field research, data analysis, peer critique, and chapter development for doctoral dissertations.', 3, 'Ongoing', 150, '700'),
('RES801', 'Dissertation Research', 'Final dissertation research, manuscript writing, and formal oral defense before faculty committee.', 3, 'Ongoing', 150, '800'),
('PHIL101', 'Introduction to Philosophy and Critical Thinking', 'Logic, argumentation, formal and informal fallacies, epistemology, and foundational Western philosophical thought.', 3, 'Ongoing', 150, '100'),
('PHIL501', 'Philosophy of Religion and Worldview', 'Advanced philosophical analysis of epistemology, religious language, divine attributes, and worldview critique.', 3, 'Ongoing', 150, '500'),
('GEN101', 'University Orientation and Academic Success', 'University life, time management, library resources, academic integrity, and digital portal navigation.', 3, 'Ongoing', 150, '100'),
('GEN102', 'Academic Study Skills', 'Reading comprehension, critical analysis, academic note-taking, and examination preparation.', 3, 'Ongoing', 150, '100'),
('COMM101', 'Communication and Public Speaking', 'Principles of verbal communication, audience analysis, persuasive speech delivery, and presentation skills.', 3, 'Ongoing', 150, '100'),
('ICT101', 'Digital Literacy and Information Technology', 'Computer fundamentals, productivity software, internet research ethics, cybersecurity, and digital communication.', 3, 'Ongoing', 150, '100'),
('MATH101', 'Quantitative Reasoning', 'Mathematical reasoning, basic statistics, financial literacy, and data interpretation for daily life and ministry.', 3, 'Ongoing', 150, '100'),
('SOC101', 'Society, Culture and Community', 'Introduction to sociology, social institutions, family structures, urbanization, and community development.', 3, 'Ongoing', 150, '100'),
('ENGL101', 'Academic Writing and Communication I', 'Grammar, sentence mechanics, expository essay construction, and academic research writing fundamentals.', 3, 'Ongoing', 150, '100'),
('ENGL102', 'Academic Writing and Communication II', 'Advanced rhetoric, persuasive research papers, APA/Turabian citations, and critical literature review.', 3, 'Ongoing', 150, '100'),
('ETHC101', 'Christian Ethics and Character', 'Biblical moral foundations, virtuous character development, honesty, integrity, and personal holiness.', 3, 'Ongoing', 150, '100'),
('DMIN701', 'Doctoral Seminar: Advanced Ministry Praxis', 'DMin core seminar integrating theological reflection with advanced pastoral praxis and applied research.', 3, 'Ongoing', 150, '700');
INSERT OR IGNORE INTO program_curriculum (id, program_id, term_number, term_id) SELECT lower(hex(randomblob(16))), 'p-dip-ministry', 1, t.id FROM academic_terms t WHERE NOT EXISTS (SELECT 1 FROM program_curriculum WHERE program_id='p-dip-ministry' AND term_number=1) LIMIT 1;
INSERT OR IGNORE INTO program_curriculum (id, program_id, term_number, term_id) SELECT lower(hex(randomblob(16))), 'p-dip-ministry', 2, t.id FROM academic_terms t WHERE NOT EXISTS (SELECT 1 FROM program_curriculum WHERE program_id='p-dip-ministry' AND term_number=2) LIMIT 1;
INSERT OR IGNORE INTO program_courses (id, curriculum_id, course_id, is_mandatory, elective_group) SELECT lower(hex(randomblob(16))), pc.id, c.id, 1, NULL FROM program_curriculum pc CROSS JOIN (SELECT id FROM courses WHERE code IN ('GEN101','ENGL101','BIBL101','THEO101','MIN101','MIN201','CHST101','SPFM201')) c WHERE pc.program_id='p-dip-ministry' AND pc.term_number=1 AND NOT EXISTS (SELECT 1 FROM program_courses px WHERE px.curriculum_id=pc.id AND px.course_id=c.id);
INSERT OR IGNORE INTO program_courses (id, curriculum_id, course_id, is_mandatory, elective_group) SELECT lower(hex(randomblob(16))), pc.id, c.id, 1, NULL FROM program_curriculum pc CROSS JOIN (SELECT id FROM courses WHERE code IN ('BIBL102','BIBL103','THEO102','PAST301','EVAN201','DISC201','LEAD201','MIN301')) c WHERE pc.program_id='p-dip-ministry' AND pc.term_number=2 AND NOT EXISTS (SELECT 1 FROM program_courses px WHERE px.curriculum_id=pc.id AND px.course_id=c.id);
PRAGMA foreign_keys = ON;
INSERT OR IGNORE INTO _migrations (name) VALUES ('0044_canonical_academic_catalogue');