-- BMI INSTITUTIONAL ROLE ACCOUNTS — PLACEHOLDER, DO NOT COMMIT CREDENTIALS.
--
-- A previous version of this file seeded eight role accounts with a committed
-- dummy credential value, which is a leak risk and breaks the no-committed-
-- credential policy (enforced by create-admin.guard.test.ts).
--
-- Create role accounts via the explicit script instead:
--
--   ADMIN_PASSWORD_HASH='<hash>' node scripts/create-admin.mjs --email registrar@bmi.edu --name "Academic Registrar"
--
-- then assign the institutional role through the UMS staff-provisioning flow
-- (POST /api/ums/staff/provision-controlled) or an admin role update.
-- The script refuses to run in production without --allow-production and never
-- prints the credential. See README.md ("Admin seeding") for details.
--
-- This file intentionally contains no INSERT and no credential value.
SELECT 1;
